name: RabbitMQ

on:
  workflow_dispatch:

concurrency:
  group: lpco-preview-infra

env:
  AWS_REGION: us-east-1

jobs:
  deploy:
    name: Deploy Preview Infra
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}


      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.3

      - name: Create or Update via Terraform
        uses: dflook/terraform-apply@v1
        with:
          path: terraform/rabbitmq
          auto_approve: true
