name: Preview Infrastructure

on:
  workflow_dispatch:


# concurrency:
#   group: lpco-preview-infra

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: rabbitmq

jobs:

  deploy:
    name: Deploy Preview Infra
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}


      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.3

      - name: Create or Update via Terraform
        uses: dflook/terraform-apply@v1
        with:
          path: terraform/preview_infra
          auto_approve: true
        #   variables: |
        #     db_username="${{secrets.DB_USERNAME}}"
        #     db_default_password="${{secrets.DB_DEFAULT_PASSWORD}}"
